### ISSUE TITLE
Test if thirdpartylibs.xml makes cibot to exclude 3rd party libs from syntax checking

### ISSUE THREAD

**Issue by mudrd8mz** [timhunt/moodle-quizaccess_offlinemode#1]
According to https://tracker.moodle.org/browse/CONTRIB-4696 there should now be support for excluding 3rd party libs in distributed thirdpartylibs.xml files. Can you please try and add such a file into your plugin? I would then run prechecker again and we can see the results. Thanks.

See https://docs.moodle.org/dev/NEWMODULE_Documentation#thirdpartylibs.xml for the reference.

**Comment by timhunt** [comment]
I think I have done this. Can you easily run pre-checker against the latest master branch?

**Comment by mudrd8mz** [comment]
I think the file name must use the plural (libs) to make it work. Currently, your master version still gives:
http://ci.stronk7.com/job/Precheck%20remote%20branch/1521/artifact/work/smurf.html
However, if I locally fix the file name to thirdpartylibs.xml, I still get
http://ci.stronk7.com/job/Precheck%20remote%20branch/1522/artifact/work/smurf.html
and I don't understand why as everything seems to be correct. I am going to discuss the issue with Eloy. In any case, the file name ought to be thirdpartylibs.xml (and that worked in other plugins we tested this with).

**Comment by timhunt** [comment]
Thanks. Renamend.
